local logger = require("logger")
local millennium = require("millennium")
local fs = require("fs")
local json = require("json")

local function resolve_plugin_dir()
    local source = debug.getinfo(1, "S").source or ""
    if source:sub(1, 1) == "@" then source = source:sub(2) end
    return source:match("^(.+)[/\\]backend[/\\][^/\\]+$")
        or fs.join(millennium.steam_path(), "millennium", "plugins", "artwork-positioner")
end

local PLUGIN_DIR = resolve_plugin_dir()
local SETTINGS_FILE = fs.join(PLUGIN_DIR, "offsets.json")
local GENERATED_CSS_FILE = fs.join(PLUGIN_DIR, "generated", "hero-position.css")
local LOGO_DATA_FILE = fs.join(PLUGIN_DIR, "logo-data.json")
local LEGACY_SETTINGS_FILE = fs.join(millennium.steam_path(), "millennium", "plugins", "hero-position", "offsets.json")
local MIGRATION_MARKER_FILE = fs.join(PLUGIN_DIR, ".hero-offsets-migrated-v1")

local function read_file(path)
    local file = io.open(path, "rb")
    if not file then return nil end
    local body = file:read("*a")
    file:close()
    return body
end

local function write_file(path, body)
    fs.create_directories(fs.parent_path(path))
    local file = io.open(path, "wb")
    if not file then return false end
    file:write(body)
    file:close()
    return true
end

local function write_file_safely(path, body)
    local temporary = path .. ".tmp"
    local previous = path .. ".previous"

    os.remove(temporary)
    if not write_file(temporary, body) then return false end

    os.remove(previous)
    if read_file(path) then
        local moved_existing = os.rename(path, previous)
        if not moved_existing then
            os.remove(temporary)
            return false
        end
    end

    local installed = os.rename(temporary, path)
    if not installed then
        if read_file(previous) then os.rename(previous, path) end
        os.remove(temporary)
        return false
    end

    os.remove(previous)
    return true
end

local function parse_offset_key(key)
    key = tostring(key or "")
    local appid = string.match(key, "^desktop%-vertical:(%d+)$")
    if appid then return "Desktop", "vertical", appid end
    appid = string.match(key, "^vertical:(%d+)$")
    if appid then return "Big Picture", "vertical", appid end
    appid = string.match(key, "^desktop:(%d+)$")
    if appid then return "Desktop", "horizontal", appid end
    appid = string.match(key, "^(%d+)$")
    if appid then return "Big Picture", "horizontal", appid end
    return nil, nil, nil
end

local function decode_offsets(body)
    if not body or body == "" then return {} end
    body = tostring(body)
    body = string.gsub(body, "^\239\187\191", "")
    body = string.gsub(body, "^%s+", "")
    body = string.gsub(body, "%s+$", "")
    local ok, value = pcall(json.decode, body)
    if not ok or type(value) ~= "table" then return {} end

    local clean = {}
    for storage_key, offset in pairs(value) do
        local key_text = tostring(storage_key or "")
        local offset_number = tonumber(offset)
        local _, _, appid = parse_offset_key(key_text)
        if appid and offset_number then
            offset_number = math.floor(offset_number + 0.5)
            if offset_number < -600 then offset_number = -600 end
            if offset_number > 600 then offset_number = 600 end
            if offset_number ~= 0 then clean[key_text] = offset_number end
        end
    end
    return clean
end

local function load_offsets()
    return decode_offsets(read_file(SETTINGS_FILE))
end

local function css_for_offsets(offsets)
    local parts = { "/* Generated by Artwork Positioner. Do not edit by hand. */" }
    local positions = {}

    for storage_key, offset in pairs(offsets) do
        local mode, axis, appid = parse_offset_key(storage_key)
        if mode and appid then
            local position_key = mode .. ":" .. appid
            positions[position_key] = positions[position_key] or {
                mode = mode,
                appid = appid,
                horizontal = 0,
                vertical = 0,
            }
            positions[position_key][axis] = offset
        end
    end

    local position_keys = {}
    for key, _ in pairs(positions) do position_keys[#position_keys + 1] = key end
    table.sort(position_keys)

    for _, position_key in ipairs(position_keys) do
        local position = positions[position_key]
        local appid = position.appid
        local selectors
        if position.mode == "Big Picture" then
            selectors = {
                "[data-artwork-positioner-bigpicture-hero-appid=\"" .. appid .. "\"]",
            }
        else
            selectors = {
                "img[src*=\"/customimages/" .. appid .. "_hero.\"]",
                "img[src*=\"/" .. appid .. "_hero.\"]",
                "img[src*=\"/" .. appid .. "_library_hero\"]",
                "img[src*=\"/librarycache/" .. appid .. "/hero\"]",
                "img[src*=\"/librarycache/" .. appid .. "/library_hero\"]",
                "img[src*=\"/apps/" .. appid .. "/library_hero\"]",
                "img[src*=\"/assets/" .. appid .. "/\"][src*=\"/library_hero\"]",
            }
        end
        local horizontal_direction = position.horizontal < 0 and "-" or "+"
        local vertical_direction = position.vertical < 0 and "-" or "+"
        parts[#parts + 1] = "/* " .. position.mode .. ": App " .. appid .. " */"
        parts[#parts + 1] = table.concat(selectors, ",\n") .. " {"
        parts[#parts + 1] = "  object-position: calc(50% " .. horizontal_direction .. " " .. tostring(math.abs(position.horizontal)) .. "px) calc(50% " .. vertical_direction .. " " .. tostring(math.abs(position.vertical)) .. "px) !important;"
        parts[#parts + 1] = "}"
    end

    return table.concat(parts, "\n") .. "\n"
end

local function persist_offsets(offsets)
    if not write_file_safely(SETTINGS_FILE, json.encode(offsets)) then
        return false, "write_settings_failed"
    end

    if not write_file_safely(GENERATED_CSS_FILE, css_for_offsets(offsets)) then
        return false, "write_generated_css_failed"
    end

    return true, nil
end

local function migrate_legacy_offsets()
    if read_file(MIGRATION_MARKER_FILE) then return end

    local legacy_offsets = decode_offsets(read_file(LEGACY_SETTINGS_FILE))
    local current_offsets = load_offsets()
    for storage_key, offset in pairs(legacy_offsets) do
        if current_offsets[storage_key] == nil then current_offsets[storage_key] = offset end
    end

    local ok, error_code = persist_offsets(current_offsets)
    if not ok then
        logger:error("Could not migrate Hero Position offsets: " .. tostring(error_code))
        return
    end
    write_file(MIGRATION_MARKER_FILE, "migrated\n")
end

local function result(ok, error_code)
    return json.encode({ ok = ok, error = error_code })
end

local function decode_logo_data(body)
    if not body or body == "" then return { version = 1, config = {}, positions = {} } end
    local ok, value = pcall(json.decode, tostring(body))
    if not ok or type(value) ~= "table" then
        return { version = 1, config = {}, positions = {} }
    end
    if type(value.config) ~= "table" then value.config = {} end
    if type(value.positions) ~= "table" then value.positions = {} end
    value.version = 1
    return value
end

function get_logo_data()
    return json.encode(decode_logo_data(read_file(LOGO_DATA_FILE)))
end

function set_logo_data(data_json)
    if type(data_json) == "table" then data_json = data_json.data_json end
    local data = decode_logo_data(tostring(data_json or "{}"))
    if not write_file_safely(LOGO_DATA_FILE, json.encode(data)) then
        return result(false, "write_logo_data_failed")
    end
    return result(true, nil)
end

function set_hero_offsets(offsets_json)
    if type(offsets_json) == "table" then offsets_json = offsets_json.offsets_json end
    local ok, error_code = persist_offsets(decode_offsets(tostring(offsets_json or "{}")))
    return result(ok, error_code)
end

function get_hero_offsets()
    return json.encode(load_offsets())
end

function set_hero_offset(appid, offset)
    if type(appid) == "table" then
        local params = appid
        appid = params.appid
        offset = params.offset
    end

    appid = tostring(appid or "")
    offset = tonumber(offset)
    local _, _, parsed_appid = parse_offset_key(appid)
    if not parsed_appid or not offset then
        return result(false, "invalid_offset")
    end

    offset = math.floor(offset + 0.5)
    if offset < -600 then offset = -600 end
    if offset > 600 then offset = 600 end

    local offsets = load_offsets()
    if offset == 0 then offsets[appid] = nil else offsets[appid] = offset end

    local ok, error_code = persist_offsets(offsets)
    return result(ok, error_code)
end

local function refresh_generated_css()
    if not write_file_safely(GENERATED_CSS_FILE, css_for_offsets(load_offsets())) then
        logger:error("Could not refresh plugin-owned Hero Position CSS: " .. tostring(GENERATED_CSS_FILE))
    end
end

local function on_load()
    logger:info("Artwork Positioner backend loaded")
    migrate_legacy_offsets()
    refresh_generated_css()
    millennium.ready()
end

local function on_frontend_loaded()
    refresh_generated_css()
end

local function on_unload()
    logger:info("Artwork Positioner backend unloaded")
end

return {
    on_load = on_load,
    on_frontend_loaded = on_frontend_loaded,
    on_unload = on_unload,
}
